# Generated by Django 5.2.5 on 2025-10-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_applications_access_delete_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications_access',
            name='msg',
            field=models.TextField(default=''),
        ),
    ]
