# Generated by Django 5.2.5 on 2025-10-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_applications_access_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications_access',
            name='cynoCovert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications_access',
            name='totalSP',
            field=models.BigIntegerField(default=0),
        ),
    ]
