# Generated by Django 5.2.5 on 2025-10-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillplans', '0002_skillplan_checklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillplan_checklist',
            old_name='Skillplan',
            new_name='skillPlan',
        ),
    ]
