# Generated by Django 5.2.5 on 2025-08-14 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(default='')),
                ('doCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DoctrineCategory', to='doctrines.categories')),
            ],
        ),
        migrations.CreateModel(
            name='FitShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipId', models.BigIntegerField(default=0)),
                ('nameFit', models.CharField(max_length=200)),
                ('desc', models.TextField(default='')),
                ('items', models.JSONField(default={})),
                ('fitCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fitCategory', to='doctrines.categories')),
                ('fitDoctrine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fitDoctrine', to='doctrines.doctrine')),
            ],
        ),
    ]
