# Generated by Django 6.0.2 on 2026-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doctrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(default='')),
                ('category', models.ManyToManyField(related_name='DoctrineCategory', to='doctrines.category')),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_id', models.BigIntegerField(default=0)),
                ('ship_id', models.BigIntegerField(default=0)),
                ('ship_name', models.CharField(default='', max_length=100)),
                ('name_fit', models.CharField(max_length=200)),
                ('desc', models.TextField(default='')),
                ('items', models.JSONField(default=dict)),
                ('min_skills', models.JSONField(default=dict)),
                ('category', models.ManyToManyField(related_name='fitCategory', to='doctrines.category')),
                ('doctrine', models.ManyToManyField(related_name='fitDoctrine', to='doctrines.doctrine')),
            ],
        ),
    ]
