# Generated by Django 5.2.5 on 2025-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0002_alter_fitship_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitship',
            name='fitId',
            field=models.BigIntegerField(default=0),
        ),
    ]
