# Generated by Django 5.2.5 on 2025-08-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0003_fitship_fitid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctrine',
            old_name='title',
            new_name='doctitle',
        ),
    ]
