# Generated by Django 5.2.5 on 2025-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0004_rename_title_doctrine_doctitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitship',
            name='fitId',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fitship',
            name='shipId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
