# Generated by Django 5.2.5 on 2025-08-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0006_alter_fitship_fitid_alter_fitship_shipid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitship',
            name='shipName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
