# Generated by Django 5.2.5 on 2025-08-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0009_remove_doctrine_docategory_doctrine_doccategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitship',
            name='fitDoctrine',
        ),
        migrations.AddField(
            model_name='fitship',
            name='fitDoctrine',
            field=models.ManyToManyField(related_name='fitDoctrine', to='doctrines.doctrine'),
        ),
    ]
