# Generated by Django 5.2.5 on 2025-09-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0010_remove_fitship_fitdoctrine_fitship_fitdoctrine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitship',
            name='min_skills',
            field=models.JSONField(default=dict),
        ),
    ]
