# Generated by Django 5.2.5 on 2025-08-29 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('group', models.ManyToManyField(related_name='SolitudGrupo', to='auth.group')),
                ('user', models.ManyToManyField(related_name='userNotification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
