# Generated by Django 5.2.5 on 2025-08-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0005_alter_fitship_fitid_alter_fitship_shipid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitship',
            name='fitId',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fitship',
            name='shipId',
            field=models.BigIntegerField(default=0),
        ),
    ]
