# Generated by Django 5.2.5 on 2025-08-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0007_fitship_shipname'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
