# Generated by Django 5.2.5 on 2025-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0008_categories_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctrine',
            name='doCategory',
        ),
        migrations.AddField(
            model_name='doctrine',
            name='docCategory',
            field=models.ManyToManyField(related_name='DoctrineCategory', to='doctrines.categories'),
        ),
        migrations.RemoveField(
            model_name='fitship',
            name='fitCategory',
        ),
        migrations.AddField(
            model_name='fitship',
            name='fitCategory',
            field=models.ManyToManyField(related_name='fitCategory', to='doctrines.categories'),
        ),
    ]
