# Generated by Django 5.2.5 on 2025-08-22 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(default=0, unique=True)),
                ('character_name', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('ban_date', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banned_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
