# Generated by Django 5.2.5 on 2025-08-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0003_bannedcharacter_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bannedcharacter',
            name='ban_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ban.bancategory'),
        ),
    ]
