# Generated by Django 5.2.5 on 2025-09-19 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0005_suspicious_suspiciousnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspiciousnotification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
