# Generated by Django 5.2.5 on 2025-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0006_alter_suspiciousnotification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspiciousnotification',
            name='suspicious_Target',
        ),
        migrations.AddField(
            model_name='suspiciousnotification',
            name='target',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Suspicious',
        ),
    ]
