# Generated by Django 5.2.5 on 2026-02-03 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sso', '0004_evecharater_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_id', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_id', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('loc_flag', models.CharField(max_length=254)),
                ('location', models.TextField(default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='sso.evecharater')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='corp.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='corp.itemgroup'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(default='')),
                ('context', models.CharField(max_length=254)),
                ('ref', models.CharField(max_length=254)),
                ('target', models.CharField(max_length=254)),
                ('date', models.DateField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transsactions', to='sso.evecharater')),
            ],
        ),
    ]
