# Generated by Django 6.0.2 on 2026-02-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0002_remove_item_group_delete_itemgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='character',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
