# Generated by Django 5.2.5 on 2025-08-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannedcharacter',
            name='character_name',
        ),
    ]
