# Generated by Django 6.0.2 on 2026-02-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0001_initial'),
        ('sso', '0005_remove_evecharater_user_character_eve_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban', to='sso.eve_character'),
        ),
    ]
