# Generated by Django 5.2.5 on 2025-08-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0002_remove_bannedcharacter_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedcharacter',
            name='character_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
