# Generated by Django 5.2.5 on 2025-09-13 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0004_bancategory_bannedcharacter_ban_category'),
        ('sso', '0003_evecharater_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspicious',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspicious_id', models.BigIntegerField(default=0, unique=True)),
                ('suspicious_name', models.CharField(max_length=255)),
                ('suspicious_type', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sso.evecharater')),
                ('suspicious_Target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ban.suspicious')),
            ],
        ),
    ]
