# Generated by Django 5.2.5 on 2025-08-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnotifications',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
