# Generated by Django 5.2.5 on 2025-08-11 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EveCharater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(default=0)),
                ('character_name', models.CharField(max_length=150)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.CharField(max_length=100)),
                ('expiration', models.TimeField(blank=True, null=True)),
                ('main', models.BooleanField(default=False)),
                ('user_character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evepj', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
