# Generated by Django 5.2.5 on 2025-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharater',
            name='allianceId',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evecharater',
            name='allianceName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='evecharater',
            name='corpId',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evecharater',
            name='corpName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='evecharater',
            name='totalSkillPoints',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evecharater',
            name='walletMoney',
            field=models.BigIntegerField(default=0),
        ),
    ]
