# Generated by Django 6.0.2 on 2026-02-24 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_evecharater_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evecharater',
            name='user_character',
        ),
        migrations.CreateModel(
            name='Eve_Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(default=0)),
                ('character_name', models.CharField(max_length=150)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.CharField(max_length=100)),
                ('expiration', models.TimeField(blank=True, null=True)),
                ('corp_id', models.BigIntegerField(default=0)),
                ('corp_name', models.CharField(default='', max_length=150)),
                ('alliance_id', models.BigIntegerField(default=0)),
                ('alliance_name', models.CharField(default='', max_length=150)),
                ('money', models.BigIntegerField(default=0)),
                ('skill_points', models.BigIntegerField(default=0)),
                ('skills', models.JSONField(default=dict)),
                ('main', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evepj', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
