# Generated by Django 6.0.2 on 2026-02-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0002_alter_character_character'),
        ('skillplans', '0004_alter_skillplan_checklist_character'),
        ('sso', '0005_remove_evecharater_user_character_eve_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EveCharater',
        ),
    ]
