# Generated by Django 5.2.5 on 2025-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_evecharater_allianceid_evecharater_alliancename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharater',
            name='skills',
            field=models.JSONField(default=dict),
        ),
    ]
