# Generated by Django 5.2.5 on 2026-01-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_evecharater_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharater',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
