# Generated by Django 6.0.2 on 2026-02-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0001_initial'),
        ('sso', '0006_delete_evecharater'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('character_FC_name', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fats_doctrine', to='doctrines.doctrine')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fats_fleetType', to='fats.fleettype')),
            ],
        ),
        migrations.CreateModel(
            name='Fat_Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship', models.CharField(max_length=200)),
                ('solar_system', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_character', to='sso.eve_character')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to='fats.fleet')),
            ],
        ),
        migrations.CreateModel(
            name='SRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srp_id', models.CharField(default='', max_length=10, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('srp_cost', models.BigIntegerField(default=0)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SRP_Fleet', to='fats.fleet')),
            ],
        ),
        migrations.CreateModel(
            name='SRP_Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zkill_id', models.BigIntegerField(default=0)),
                ('ship_id', models.BigIntegerField(default=0)),
                ('ship_name', models.CharField(default='', max_length=200)),
                ('zkill_value', models.BigIntegerField(default=0)),
                ('srp_cost', models.BigIntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SRP_Pilot', to='sso.eve_character')),
                ('srp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SRP_Ship', to='fats.srp')),
            ],
        ),
    ]
