# Generated by Django 5.2.5 on 2025-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fats',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fleettype',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
