# Generated by Django 5.2.5 on 2025-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillplans', '0001_initial'),
        ('sso', '0003_evecharater_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillplan_CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('Skillplan', models.ManyToManyField(related_name='skillplan_name', to='skillplans.skillplan')),
                ('character', models.ManyToManyField(related_name='character_skillplan', to='sso.evecharater')),
            ],
        ),
    ]
