# Generated by Django 6.0.2 on 2026-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillplans', '0003_rename_skillplan_skillplan_checklist_skillplan'),
        ('sso', '0005_remove_evecharater_user_character_eve_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillplan_checklist',
            name='character',
            field=models.ManyToManyField(related_name='character_skillplan', to='sso.eve_character'),
        ),
    ]
