# Generated by Django 5.2.5 on 2025-08-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0010_remove_fitship_fitdoctrine_fitship_fitdoctrine'),
        ('sso', '0002_evecharater_allianceid_evecharater_alliancename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solarSystem', models.CharField(max_length=200)),
                ('ship', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fats_character', to='sso.evecharater')),
                ('characterFC', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fats_characterFC', to='sso.evecharater')),
                ('doctrine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fats_doctrine', to='doctrines.doctrine')),
                ('fleetType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fats_fleetType', to='fats.fleettype')),
            ],
        ),
    ]
