# Generated by Django 5.2.5 on 2025-09-22 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fats', '0002_fats_name_alter_fleettype_name'),
        ('sso', '0003_evecharater_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srp_id', models.CharField(default='', max_length=10, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('srp_cost', models.BigIntegerField(default=0)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SRP_Fleet', to='fats.fats')),
            ],
        ),
        migrations.CreateModel(
            name='SRPShips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zkill_id', models.BigIntegerField(default=0)),
                ('ship_id', models.BigIntegerField(default=0)),
                ('ship_name', models.CharField(default='', max_length=200)),
                ('zkill_value', models.BigIntegerField(default=0)),
                ('srp_cost', models.BigIntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SRP_Pilot', to='sso.evecharater')),
                ('srp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SRP_Ship', to='fats.srp')),
            ],
        ),
    ]
