# Generated by Django 5.2.5 on 2025-10-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fats', '0003_srp_srpships'),
        ('sso', '0003_evecharater_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fats',
            name='character',
        ),
        migrations.RemoveField(
            model_name='fats',
            name='ship',
        ),
        migrations.RemoveField(
            model_name='fats',
            name='solarSystem',
        ),
        migrations.CreateModel(
            name='Fats_Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship', models.CharField(max_length=200)),
                ('solarSystem', models.CharField(max_length=200)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_character', to='sso.evecharater')),
                ('fat', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fat', to='fats.fats')),
            ],
        ),
    ]
