# Generated by Django 5.2.5 on 2025-10-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fats', '0004_remove_fats_character_remove_fats_ship_and_more'),
        ('sso', '0003_evecharater_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fats_character',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_character', to='sso.evecharater'),
        ),
        migrations.AlterField(
            model_name='fats_character',
            name='fat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fat', to='fats.fats'),
        ),
    ]
